### ISSUE TITLE
[CheckJira] Unable to add comment

### ISSUE THREAD

**Issue by stevenpost** [gnustavo/Git-Hooks#27]
Hi,

I'm trying out the git hooks for Jira integration, but I'm unable to make a comment appear in an issue.
No error is given (post-receive hook), but as soon as I change any other config item, githooks (rightfully) complains about the various checks in place.
Investigating this, I noticed an 'anomaly' on line 411 of the CheckJira code, where the variable '$PKG' is passed to retrieve the configuration of 'comment', but on all other occasions, the variable '$CFG' is used for this. Is this a proper bug or do I need to look somewhere else?

Disclaimer: I'm not a PERL expert.

Regards,
Steven

**Comment by mikkoi** [comment]
Unfortunately I don't have the chance to use and test the hook in my current setup and environment anymore.
It looks like that ($PKG) would be the problem, though. Well observed!

**Comment by gnustavo** [comment]
Hi Steven and Mikko.

Yes, it is a bug. I just released Git::Hooks 1.12.5 fixing it. The new release should appear shortly at CPAN.

Thanks!

**Comment by stevenpost** [comment]
Thanks, after a bit of debugging, there is still an issue here.

in the function notify_ref:
    foreach my $commit ($git->get_affected_ref_commits($ref)) {
        $errors += notify_commit_msg($git, $commit, $ref, $visibility);
    }

The code doesn't seem to enter that foreach loop, when doing a poor man's debug (print), the value returned from the get_affected_ref_commits call is 0.
my $stuff = $git->get_affected_ref_commits($ref);
print "$stuff \n";

The $ref variable itself appears correct: refs/heads/testjira
So does the $git variable: Git::More=HASH(0x1bbfd70)

**Comment by gnustavo** [comment]
Hmm... you're right. Shame on me, I don't have tests to check CheckJira's post-receive hook. ;-)

I investigated and found the root cause. During the post-receive hook the remote repository's local references are already modified. The Git::More::get_commits function, used by get_affected_ref_commits, assumes that the references aren't modified yet.

I'll have to think a bit more about this to solve it. I can't guarantee that it'll be today, though.

Thanks!

**Comment by stevenpost** [comment]
Hi,

Have you had the chance to think about it?
My colleague wrote an additional script that allows you to close a ticket, maybe we can contribute this as well.

We would like to use this to integrate git and Jira in our puppet setup, although this would require a working post-receive hook ;)

Regards,
Steven

**Comment by gnustavo** [comment]
Hi Steven. I'm sorry for having taking so long. But I think I fixed it now. I just released version 1.13.1 which should appear shortly at CPAN.

Please, test it out and let me know if it works for you.
